#!/usr/bin/env bash

set -eu

singularity exec -B img/trinity_2.6.6.simg \
        abundance_estimates_to_matrix.pl \
 	--est_method RSEM \
 	--cross_sample_norm none \
 	--out_prefix output/trinity_abundance/RSEM \
 	output/trinity_abundance/RSEM.isoforms.results
  ##check it won't overwirte RESEM.isoforms.results - think this is input but worht checking.
