#!/usr/bin/env bash


set -eu


singularity exec -B /Volumes img/clustalo_1.2.4.simg clustalo \
	-i clustalo_input/all_hox \
	--out output/clustalo/all_hox_aligned.fasta \
	--threads=20 \
	&> output/logs/clustalo
