#!/usr/bin/env bash


set -eu


singularity exec -B /Volumes img/clustalo_1.2.4.simg trimal \
	-in output/clustalo/2nd_alignment.fasta \
	-out output/clustalo/trimal.fasta \
	-fasta \
	-gappyout \
	&> output/logs/trimal
