#!/usr/bin/env Rscript
library(data.table)

x <- fread("trinotate_annotation_report.txt")
x[sprot_Top_BLASTX_hit != ".", length(unique(transcript_id))]
x[sprot_Top_BLASTP_hit != ".", length(unique(transcript_id))]
x[, length(unique(transcript_id))]
x[, length(unique(`#gene_id`))]

