#!/usr/bin/env bash

set -eu

singularity run -B /Volumes img/trinity_2.6.6.simg \
    --SS_lib_type RF \
    --max_memory 500G \
    --CPU 20 \
    --output output/trinity \
    --left output/bbmerge/s1_r1_all.fq.gz \
    --right output/bbmerge/s1_r2_unmerged.fq.gz \
    --seqType fq \
    &> output/logs/trinity_early.log

