#!/usr/bin/env bash

set -eu

singularity exec -B img/trinity_2.6.6.simg \
        TrinityStats.pl \
	output/trinity/Trinity.fasta \
	> output/trinity_stats/stats.txt

singularity exec -B img/trinity_2.6.6.simg \
        contig_ExN50_statistic.pl \
	output/trinity_abundance/RSEM.TPM.not_cross_norm \
	output/trinity/Trinity.fasta \
	>output/trinity_stats/xn50.out.txt \
	2>output/logs/trinity_quality_exn50.log


